version: "3"

networks:
    back:

volumes:
  soundhive_pg:
  soundhive_minio:

services:
  front:
    build:
      context: .
      args:
        ENV: development
    container_name: soundhive-front
    ports:
      - "8080:8080"
  back:
    build:
      context: ./api/
      dockerfile: ./api/Dockerfile
    container_name: soundhive-back
    ports:
      - "3000:3000"
    networks:
      - back
    depends_on:
      - minio
      - db

  db:
    image: postgres:13-alpine
    networks:
      - back
    volumes:
      - ./soundhive_pg:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGPORT=${DB_PORT}
      - POSTGRES_USER=${POSTGRES_USER}

  minio:
    image: minio/minio
    volumes:
    - soundhive_minio:/data
    environment:
      MINIO_ACCESS_KEY: miniokey
      MINIO_SECRET_KEY: miniosecret
    command: server /data
    # ports:
    #   - 127.0.0.1:9000:9000
    networks:
      - back
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    restart: always



